### ISSUE TITLE
Compose window no longer closing

### ISSUE THREAD

**Issue by pkedrosky** [dangeredwolf/ModernDeck#130]
Looks like something has changed, perhaps at twitter end, and the compose window no longer closes in standalone ModernDeck. 

![2019-05-16_09-59-47](https://user-images.githubusercontent.com/3206644/57872916-b294cb00-77c1-11e9-9c53-806901b344ef.png)

**Comment by dangeredwolf** [comment]
Whoops, didn't see the issue you filed, since you sent to me via Twitter as well anyhow, but this has been already fixed in 7.0.1. Thank you for reporting this bug!
