### ISSUE TITLE
Two real issues with ModernDeck

### ISSUE THREAD

**Issue by chazzbro** [dangeredwolf/ModernDeck#137]
After 10-15 seconds, the cursor jumps back to close to the beginning of the text while typing. Very irritating.

When choosing an emoji and having done so, there is no obvious way to collapse that popout...making it quite a challenge to track down the Send arrow (which isn't always something you're ready to do anyway). There ought to be a clear way to close that emoji box.

**Comment by dangeredwolf** [comment]
yes, I am aware about the cursor jumping issue, and I will need to find a fix for it.

As for the emojis, clicking the emoji button closes the menu just as it opens it.

What version are you running? Ctrl+Alt+D will tell you as the first thing in the diagnostic report, or using Settings > About

**Comment by chazzbro** [comment]
Version 7.4.1

 

Thanks for the tip about using the emoji button. Hadn’t thought of that.

 

 

Chuck Brown

Voice Over Demos:  <http://chuckbrownvoiceover.com/> ChuckBrownVoiceover.com

My Music:  <http://chuckbrownmusic.com/> ChuckBrownMusic.com
My Music Videos for Kids:  <https://tinyurl.com/chuckleberries> TinyURL.com/chuckleberries

**Comment by dangeredwolf** [comment]
You'll be happy to know that I fixed the jumping cursor in ModernDeck 8 :)

**Comment by chazzbro** [comment]
Excellent. I’ll be watching for that. I noticed it jumping again last night and wondered if you were working on it. 😊

C-

 

Chuck Brown

Mobile: (614) 580-4689 | Fax: (201) 530-8307

Voice Over Demos:  <http://chuckbrownvoiceover.com/> ChuckBrownVoiceover.com

My Music:  <http://chuckbrownmusic.com/> ChuckBrownMusic.com
My Music Videos for Kids:  <https://tinyurl.com/chuckleberries> TinyURL.com/chuckleberries

**Comment by chazzbro** [comment]
Hope it’s coming soon! It’s still very frustrating! LOL

 

Chuck Brown

Mobile: (614) 580-4689 | Fax: (201) 530-8307

Voice Over Demos:  <http://chuckbrownvoiceover.com/> ChuckBrownVoiceover.com

My Music:  <http://chuckbrownmusic.com/> ChuckBrownMusic.com
My Music Videos for Kids:  <https://tinyurl.com/chuckleberries> TinyURL.com/chuckleberries

**Comment by dangeredwolf** [comment]
ModernDeck 8 will be released 30 May 2020, I'm putting finishing touches as well as coordinating with translators so it launches in several languages.

**Comment by chazzbro** [comment]
Excellent. Thanks!

 

C-

 

Chuck Brown

Mobile: (614) 580-4689 | Fax: (201) 530-8307

Voice Over Demos:  <http://chuckbrownvoiceover.com/> ChuckBrownVoiceover.com

My Music:  <http://chuckbrownmusic.com/> ChuckBrownMusic.com
My Music Videos for Kids:  <https://tinyurl.com/chuckleberries> TinyURL.com/chuckleberries
