### ISSUE TITLE
GIF (Giphy) selector doesn't work

### ISSUE THREAD

**Issue by cmdrfletcher** [dangeredwolf/ModernDeck#163]
shows

An error occurred while trying to fetch results.[object Object]

![image](https://user-images.githubusercontent.com/6803995/87182137-d67b7000-c2e3-11ea-8628-46030085ec30.png)

Version 8.0.3

**Comment by dangeredwolf** [comment]
I appreciate the heads up! Twitter changed their content security policy in a way that I can't fetch GIFs anymore. The fix is being backported from 8.1 Beta to 8.0.x and a fix will be available soon!

**Comment by dangeredwolf** [comment]
This issue was fixed in 8.0.4. It should be available on Firefox shortly, and Chrome once they get around to reviewing it, and hopefully not reject it.

**Comment by cmdrfletcher** [comment]
It works again. :)
