### ISSUE TITLE
Topics: Appear in Home Column or Possibility to Add as Separate Column

### ISSUE THREAD

**Issue by IRlyLikeBac0n** [dangeredwolf/ModernDeck#174]
Not sure if this is an intended "bug" on Twitter's end, but I don't think I see any of my followed topics in my Home column. 

I also think it would be really useful to allow topics to be added as a separate column, but I'm wary that TweetDeck itself lacks this function. Just throwing the idea out there in case there may be a creative way to hack something together.

**Comment by dangeredwolf** [comment]
I'm not sure if this is possible to implement because ModernDeck is built on top of TweetDeck. I'm going to guess no, given that Topics management to my knowledge isn't a public API either. :(

**Comment by dangeredwolf** [comment]
As much as I'd like to implement it, it's just unfeasible given the current state of TweetDeck. Sorry about that.
