### ISSUE TITLE
On Linux, from version 9.1 screen doesn't refresh on open

### ISSUE THREAD

**Issue by WebShapedBiz** [dangeredwolf/ModernDeck#177]
Hi.
It seems like the same problem with newer versions of Google Chrome on Linux having hw acceleration enabled, when clicking on Open ModernDeck the widow opens but without content. Resizing the window, thus refreshing the content, solves this issue but it's annoying as hell. This has never happened before.

Screencast here: https://www.screencast.com/t/FD6s0muRpZ

Cheers.

**Comment by dangeredwolf** [comment]
Uh oh, that's not good.

That sounds like an issue with Chromium/Electron that's affecting both Chrome and ModernDeck...

What are your hardware specs and distro?

**Comment by WebShapedBiz** [comment]
Thank you @dangeredwolf for your reply. Here are my specs:

OS: elementary OS 5.1.7 Hera x86_64 
Host: HP ProOne 400 G1 AiO 
Kernel: 5.4.0-59-generic 
Shell: bash 4.4.20 
Resolution: 1600x900 
DE: Pantheon 
WM: Mutter(Gala) 
CPU: Intel i3-4130T (4) @ 2.900GHz 
GPU: Intel HD Graphics 4400 
Memory: 3143MiB / 11903MiB 

Cheers.

**Comment by dangeredwolf** [comment]
Thanks!

I'll see what I can do to try to reproduce the issue. I'm not sure if it's the OS messing up in general or because of your hardware.  If I can reproduce it I'll pass it on to the Chromium guys.

**Comment by WebShapedBiz** [comment]
Thank you @dangeredwolf for your time and effort.
I've also tested a few theories and one paying the dividend was to remove `xserver-xorg-video-intel` from my computer, making this particular problem with ModernDeck went away, and everything is fine now. However, some of the old problems, not related to ModerDeck or Electron apps, came back with it, but that's another story.

I hope you can make some sense of this info because I don't have the required knowledge to do so.

Cheers.

**Comment by dangeredwolf** [comment]
Hi, sorry it's been a while. Is this issue still relevant on the latest version of your distro?

**Comment by WebShapedBiz** [comment]
Everything is working fine now, thank you @dangeredwolf
