### ISSUE TITLE
Music easter egg interfering with keybinds I use elsewhere

### ISSUE THREAD

**Issue by aaaddd4747** [dangeredwolf/ModernDeck#179]
I would like to request the option to disable this easter egg, or at least stop the music without refreshing the page. its bound to the same keys as my mic mute. modern deck is pretty great otherwise aside from this admittedly rather amusing issue.

**Comment by dangeredwolf** [comment]
Oh my gosh, I'm so sorry haha. Will definitely fix this.

**Comment by dangeredwolf** [comment]
In 9.1.2 I removed the music easter egg. It hadn't been updated since ModernDeck 8 anyway

**Comment by dangeredwolf** [comment]
For now, the PS2 easter egg does still work.
