### ISSUE TITLE
appearance settings menu has overlapping items in some conditions

### ISSUE THREAD

**Issue by aaaddd4747** [dangeredwolf/ModernDeck#183]
as per the twitter thread on this topic: https://twitter.com/QuixoticWolve/status/1355728241596706818
![EtCvUTLUUAIBRps](https://user-images.githubusercontent.com/12995040/106400393-7103e380-63db-11eb-89b0-dcf6ac5a3e1e.png)

based on my testing i believe this to be an issue relating to the width of the text labels vs the remaining available space. 
the issue requires "scrollbar style" to be set to "original" (my preferred setting), and any of the following fonts to be set:

- roboto
- roboto slab
- roboto mono
- noto sans
- open sans
- lato
- jost
- system ui (i dont know what my system font is)

the issue does **NOT** occur with roboto condensed.

the issue seems to be invariant of total window width (i use the firefox plugin "Tree Style Tab" so my window wdth is non standard).

also of note in this same screenshot: the font size slider is messed up. the lower limit of the slider and the slider itself are placed too far down and to the right while the upper limit is placed correctly. the slider itself clips into the reset button, layered behind.
this secondary issue seems to have the same conditions causing it, and actually may be whats causing the other menu items to overlap as it shimmies the entire pfp size selector slider down as well

on even closer inspection all sliders on the page are affected. the sliders are too wide for the menu as a whole and should be resized to fit the smaller width.

the menu shown correctly for comparison:
![image](https://user-images.githubusercontent.com/12995040/106401022-0eace200-63df-11eb-930c-93563de14a08.png)

**Comment by dangeredwolf** [comment]
I believe I fixed this but forgot to close the issue, so I'll do that now. If the bug can still be reproduced under other conditions I can reopen it.
