### ISSUE TITLE
ModernDeck shows "App" settings in browsers

### ISSUE THREAD

**Issue by panos** [dangeredwolf/ModernDeck#185]
Dear maintainer,

As you noticed @uwueviee clearly demonstrate right in front of your bare eyes, the "App" section in the Settings is visible when installing the ModernDeck extension in Firefox.

Moreover, the native bar is also possibly enabled.

See:

https://github.com/dangeredwolf/ModernDeck/blob/21ac834792edee7048fbadfcc9b103ca18bb2924/src/DataSettings.js#L669
https://github.com/dangeredwolf/ModernDeck/blob/21ac834792edee7048fbadfcc9b103ca18bb2924/src/DataSettings.js#L684
https://github.com/dangeredwolf/ModernDeck/blob/21ac834792edee7048fbadfcc9b103ca18bb2924/src/DataSettings.js#L862
https://github.com/dangeredwolf/ModernDeck/blob/21ac834792edee7048fbadfcc9b103ca18bb2924/src/DataSettings.js#L878
https://github.com/dangeredwolf/ModernDeck/blob/21ac834792edee7048fbadfcc9b103ca18bb2924/src/DataSettings.js#L669

**Comment by dangeredwolf** [comment]
oops I forgot to close this, I already fixed it lol
