### ISSUE TITLE
Resize media in a tweet

### ISSUE THREAD

**Issue by RagnarBelial** [dangeredwolf/ModernDeck#211]
I don't seem to find if this was already pointed out, so I'm doing it myself. 
Is there a setting that would resize the picture in a tweet, so you don't have to click on it to see the whole thing?

**Comment by dangeredwolf** [comment]
When you open the tweet details it should display as much of the image as can fit in the box, though for some awkward sizes it might be too hard to read (i.e. something 10 pixels high but 200 pixels wide). If there's another behavior you'd like implemented I'd like to learn more about it cause I'm not sure if I fully understand what you are asking

**Comment by RagnarBelial** [comment]
Ah, sorry, I am completely stupidly explaining what I meant. 
The thing is, for example, a gif reply to a tweet. You would only see a whatever pixel height is set to it. 
When you click on it, it starts playing, but still in the same height. Is it possible to have it open for playing so you don't just see a third or a quarter of it? 

![Screenshot from 2022-03-23 16-53-12](https://user-images.githubusercontent.com/99590667/159753596-be93d3cb-bcdb-4ba9-b73b-8e9dee9a79dd.png)

**Comment by dangeredwolf** [comment]
You could also change the media size in the column settings to help with that.
