### ISSUE TITLE
Scrollbar not hiding

### ISSUE THREAD

**Issue by dnestico** [dangeredwolf/ModernDeck#216]
I have scrollbars set to hidden but it doesn't seem to be working. I'm using the mac app.'

The setting:
![Screen Shot 2022-03-23 at 9 56 45 PM](https://user-images.githubusercontent.com/3034555/159826676-218a66a5-176a-444e-b008-9c88a061982b.png)

See, they're not hidden:
![Screen Shot 2022-03-23 at 9 56 56 PM](https://user-images.githubusercontent.com/3034555/159826685-49a46d38-acf0-41a3-a346-1b4df99b31af.png)

**Comment by dnestico** [comment]
UPDATE:

I got them to hide with some WebKit CSS! 

Now just wondering what the CSS is to move the tweet drawer a little lower cuz I don't like how high it is but its good enough for now.


The CSS used:

![Screen Shot 2022-03-23 at 10 09 19 PM](https://user-images.githubusercontent.com/3034555/159828146-97f53fd1-cc3c-44fc-af44-02fbc94841b5.png)

Here is the code:

`::-webkit-scrollbar {
    display: none;
}`

Result:

![Screen Shot 2022-03-23 at 10 09 43 PM](https://user-images.githubusercontent.com/3034555/159828155-3c8e784a-5492-4ed8-aa20-0526f184465a.png)

**Comment by dangeredwolf** [comment]
I'll actually integrate that change into ModernDeck so people don't have to do that, thanks for the bug report!

**Comment by dnestico** [comment]
Nice!
