### ISSUE TITLE
[bug] Design color can not be changed

### ISSUE THREAD

**Issue by charasche** [dangeredwolf/ModernDeck#233]
Unfortunately, when I go to Settings -> Themes -> Design Colour to change the colour, nothing changes (although the new colour is shown as selected). Even after restarting the application, the colour does not change.

![moderndeck](https://user-images.githubusercontent.com/102631683/161428665-bb8b2254-d5c6-4b95-b2e3-897af97c86ac.jpg)

OS: Fedora 35 workstation
DE: GNOME 41.5
Version: Version 9.4.1 (Build 1513)
Installed via: [flathub.org](https://flathub.org/apps/details/com.dangeredwolf.ModernDeck)

**Comment by dangeredwolf** [comment]
I've figured out what is causing this issue and I'm working on a fix 👍

**Comment by dangeredwolf** [comment]
Forgot to click close :+1:
