### ISSUE TITLE
Interface Issues in FF?

### ISSUE THREAD

**Issue by megaRammy** [dangeredwolf/ModernDeck#25]
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:33.0) Gecko/20100101 Firefox/33.0.2 Waterfox/33.0

Top bar often pushed off the top of the screen on refresh, with excess padding at bottom. Issue resolves when the slither of New Tweet button is pressed, and the sidebar is pulled in.

![Example](https://cloud.githubusercontent.com/assets/3588983/6805024/c7da90d6-d238-11e4-85a9-21408e78685d.PNG)

After transitioning from column view to tweet detail(?), interface buttons become "sticky", requiring numerous clicks to activate.

**Comment by dangeredwolf** [comment]
Sorry for how extremely late this response is. Jumono is helping create an all new modern FF version for TDE.

**Comment by jumono** [comment]
We're still working on a fully working port, since the CSS was mostly written for chrome, there still need some tweaks to make it fully compatible with Firefox, sorry for the issue.

**Comment by megaRammy** [comment]
Fair enough, hope to see the fruits of this labour soon!
