### ISSUE TITLE
Hide pictures

### ISSUE THREAD

**Issue by Damrak1** [dangeredwolf/ModernDeck#263]
ModernDeck would be perfect if it were possible to hide profile pictures, or reduce their size to 0px instead of 24px.

**Comment by dangeredwolf** [comment]
Thanks for the suggestion. This shouldn't be too difficult to add so I'll probably do it.

**Comment by dangeredwolf** [comment]
Thanks for the suggestion, I've implemented this now and it'll show up in the next 10.0 beta.
