### ISSUE TITLE
Moderndeck not showing up

### ISSUE THREAD

**Issue by folfgirl** [dangeredwolf/ModernDeck#291]
after I install the flatpak for moderndeck I try and look it up in my application launcher it does not show up. I run arch 5.15.40-1

**Comment by dangeredwolf** [comment]
What desktop environment are you using?

**Comment by folfgirl** [comment]
I am using plasma-Kde

**Comment by folfgirl** [comment]
I think it has to do with the fish shell because it is now working but I am using a work around. my default was fish now I changed it to zsh but my terminal starts fish.
