### ISSUE TITLE
New tweets pile on top

### ISSUE THREAD

**Issue by WcDuck** [dangeredwolf/ModernDeck#33]
How about a feature that would pile new tweets on top of the most recent tweet? In other words, a feature that would prevent Tweetdeck from pinning to top and allow users easily to read new tweets, right from where left off.

There is a "workaround" to scroll just a bit down so Tweetdeck doesn't automatically keep timeline in the uppermost position, but it's tedious in a long term.

**Comment by mralext20** [comment]
There's a setting for this on tweet deck, called something like auto refresh.

**Comment by WcDuck** [comment]
If you mean streaming, that's not quite what I mean. Even if streaming is disabled, it still pins to top. Just loads tweets a bit slower.

**Comment by dangeredwolf** [comment]
This would be an interesting thing to have, and it's definitely something to consider implementing
