### ISSUE TITLE
TDE deletes TD and replaces it with its own web app?

### ISSUE THREAD

**Issue by antolovich** [dangeredwolf/ModernDeck#36]
This may only relate to installing TDE through the OSX installer.

After installing TDE, I noticed a couple things.  

First, when you launch TD, it opens another application that appears to be a skinned instance of either Chrome or Firefox (I'm not sure which, I already uninstalled TDE) that is made it look like its actually running the TD application.  

Secondly, if the TD icon is kept in the dock, then there will be two icons in the dock after launching, one for TDE's imitation of the TD application and one of the TDE's skinned browser instance.

If this is the intended behavior, it should definitely be documented that TDE removes TD and replaces it with an application that impersonates TD (similar icons and same application file name) that only launches a skinned browser instance, and not actually a native application, or the real TD.

**Comment by dangeredwolf** [comment]
Sorry. It was intended for installation on computers without the TweetDeck app installed from the app store before.

**Comment by dangeredwolf** [comment]
TDE for OS X is a skinned Google Chrome Canary. It's designed to not mess with your existing browser configuration. It uses google chrome canary to install in another directory, so that it is completely separate from your Google Chrome configuration if you have one.

**Comment by dangeredwolf** [comment]
The current TDE for OS X is the best I could deliver, as there isn't currently a better solution available. TDE for Safari is still buggy, and an integrated UIWebView wouldn't be of much help quite yet. Eventually I'd like to make it a native application with a standard UIWebView.

**Comment by antolovich** [comment]
Yes. I figured that out after I installed it.  Everything that it does I would consider to be fine, just as long as there is documentation somewhere that shows it.  I downloaded it and installed it without looking at any of the code, with the end result being TD was uninstalled, replaced with an app that looks like TD,  it moved my currently installed Chrome configuration to a backup folder, replacing it with a modified version.

I understand the limitations involved.  I also understand what the Automator application does.  However, I hope you can see how not informing users that it is going to delete the real TD application, and also replace the current installed chrome configuration with a modified version, can cause problems for some users.  If my technical knowledge was limited, I would not have been able to restore my "lost" data.  

I would still say though that this is a bug.  The first bug is that there is no documentation to say what the installer is doing (replacing the TD native app with a skinned browser).  The second bug, and this is the most important one, is that running the installer replaces the existing Chrome configuration (albeit keeping a backup).

**Comment by jumono** [comment]
Sounds like something I'm going to work on tonight then.

**Comment by dangeredwolf** [comment]
Do you know how to use chromium embedded? That'll be handy

**Comment by jumono** [comment]
I'll try the best I can.
