### ISSUE TITLE
Will there be updates?

### ISSUE THREAD

**Issue by derN3rd** [dangeredwolf/ModernDeck#41]
Hey dangeredwolf,
I just saw that you're still alive and i was just curious whether you will do updates or not.
![2015-12-11_16-15-34](https://cloud.githubusercontent.com/assets/7534045/11747323/e8109392-a022-11e5-93ae-4db26774e067.png)
Both websites used in ModernDeck are offline and now even the design starts to break.

Thanks in advance

**Comment by jumono** [comment]
There will be update soon, I'm currently the new owner of ModernDeck and I'll try my best to update it as soon as possible, I'm working on two huge project side by side and I'll do my best to fix that issue and some others. You should except an update soon.
Thanks you for using ModernDeck and have a nice day.

**Comment by mfehmer** [comment]
@jumono I'm really glad to hear this!
Good luck for you and Your projects :)

Have a nice day

**Comment by coolstar** [comment]
Download "Stylish" and inject this into tweetdeck.twitter.com: https://ghostbin.com/paste/xe7xe

**Comment by mfehmer** [comment]
@coolstar Works perfectly! Thanks for sharing

**Comment by derN3rd** [comment]
@jumono Hey, ModernDeck breaks every day a bit more. Do you know when you release a fix for the current bugs?

Thanks in advance

**Comment by coolstar** [comment]
@derN3rd are you running my fix? Has there been anything you noticed that broke recently?

**Comment by derN3rd** [comment]
@coolstar Yes I am, but the popup menu (when you open one direct message and select "...") is also broken.
Also gifs (sometimes even normal pictures) are having a big visible padding at the bottom, and in picture full view the popup ist streched over the whole height.
But my main problem is with the dms

**Comment by coolstar** [comment]
@derN3rd just tested those here with latest TDE + my fix on Chrome 48/Windows 10. Don't see any of those issues. Are you sure you're running my fix in Stylish?

**Comment by derN3rd** [comment]
Now i reinstalled ModernDeck (pulled into a new folder and tried to use it in chrome) but now it is completely messed up (like there isnt even any css):
![Screenshot](http://maxfehmer.de/u/c7fcb990930314699fdd36aef82f0213.png)

(And yes, I'm running your fix)

**Comment by coolstar** [comment]
I'm using ModernDeck from the Chrome Web Store

**Comment by derN3rd** [comment]
When I use the WebStore Version, the bug isn't fixed with your code.

![Screenshot](http://maxfehmer.de/u/01cbe15ab3770e297535979dee125362.png)

**Comment by pixeldesu** [comment]
to inform you, there most likely won't be any updates to ModernDeck anymore.

@dangeredwolf, the person who started the project handed it over to someone else, but they left it in a pretty much unmaintainable state. It's really hard to fix the CSS or other issues when there's a single file with 11k lines of styling. I wanted to refactor it myself, but...it's impossible with a file this large, it would take way too much effort than valuable for the project.

To lighten up the future a bit, @jumono, the new project maintainer, is instead of working on ModernDeck, working on an entirely own client that will be theme-able etc.

**Comment by kirb** [comment]
The [TDE6](https://github.com/dangeredwolf/ModernDeck/tree/TDE6) branch was an attempt to have the styles as an overlay. Makes it way easier to maintain (at the cost of the browser having to process more style rules, sadly). Not fully ported across, but it’s something.

**Comment by pixeldesu** [comment]
@kirb okay, TDE6 looks way cleaner since it uses SCSS, but is it a full port of everything from TDE5?

**Comment by kirb** [comment]
Don’t remember the exact state of it. If memory serves correct it was maybe 40% ported.

Running a prettifier on the original TweetDeck CSS and TDE5 equivalent and then diffing would help a lot to work out what should be overridden. If I recall correctly it did also merge both color schemes into one stylesheet so factor that in too.

**Comment by pixeldesu** [comment]
In my opinion, if there should be any work on TDE, it should be a complete rewrite.

The JS is really messy and considering all the checks if stuff is existing or not, that get chained into infinity, makes it way harder to actually work with it.

It would also require constant upkeep with the changes TweetDeck makes. They are mostly minor, but still sometimes break the custom CSS aspects of userstyles etc.

**Comment by kirb** [comment]
I had [a fork](https://github.com/hbang/Condor/tree/0bee8fac3fae3f544dfd2016b6670dd79ee95f30) due to some disagreements; it mostly became the basis of TDE6 in the end. In particular I [rewrote content.js](https://github.com/hbang/Condor/blob/0bee8fac3fae3f544dfd2016b6670dd79ee95f30/extension/content.js) for that reason. It doesn’t support everything TDE5 does though (I intentionally removed some features).

**Comment by pixeldesu** [comment]
For most, a lot of the javascript code was unnecessary anyway, the CSS did most of it and the JS was used to implement extra elements, which had almost no big role except for adding more overhead.

I figured something out for this. You simply can add the version-hash for TweetDeck into a config variable and the script would check if it matches with it. If it doesn't it could either:

* give a notification popup saying that the current TweetDeck revision is potentially unsupported
* do the same as above, just as console output, so it won't annoy end-users

Anyway, do you have any way I can contact you outside the issues somewhere, like Twitter or something? Just for discussing further. I'm [@pixeldesu](https://twitter.com/pixeldesu) there (obviously).

**Comment by dangeredwolf** [comment]
Updated and fixed. Sorry about the wait.
