### ISSUE TITLE
ModernDeck Settings options not working

### ISSUE THREAD

**Issue by sidspyker** [dangeredwolf/ModernDeck#49]
Hi there, I am using the newest stable Chrome with a separate profile for Tweetdeck as an app so ModernDeck is the only Extension installed, I was using BetterTweetdeck before this until today.

All the avatars are rounded by default but it's not ticked in the settings, and ticking any option at all does nothing, as soon as I close ModernDeck settings window and reopen it again, they're all unchecked.

I thought maybe it was because of cache or remnants of BetterTweetdeck so I cleared all the data from the Tweetdeck profile and started afresh but the issue persists.

[The extension was installed from the web store, not manually.]

**Comment by dangeredwolf** [comment]
Fixed in 6.0, I forget if I backported the fix, but 6.0 is right around the corner anyways.
