### ISSUE TITLE
DM Dropdown Overflow

### ISSUE THREAD

**Issue by derN3rd** [dangeredwolf/ModernDeck#59]
Hey there, I just wanted to report an issue with the dropdown menu on a single DM.
The dropdown is hidden behind the content.

![chrome_2016-05-10_12-16-51](https://cloud.githubusercontent.com/assets/7534045/15143314/4e56bd32-16a9-11e6-8457-ce5264d4bf4e.png)

EDIT:
Looks like the quoted retweet (only the design) is also broken now...
![chrome_2016-05-10_12-19-53](https://cloud.githubusercontent.com/assets/7534045/15143365/9de27986-16a9-11e6-8cf9-d932f71c1c37.png)

Thanks in advance

**Comment by seijimaddog** [comment]
I can confirm this. I was about to report the same issue.

**Comment by dangeredwolf** [comment]
Fixed in an earlier 6.0 build. And the second issue was also fixed in 6.0 RC1.
