### ISSUE TITLE
Can't use inline reply when confirmation step is set

### ISSUE THREAD

**Issue by seijimaddog** [dangeredwolf/ModernDeck#60]
I have an account with the confirmation step set on Tweetdeck settings. The confirmation toggle is displayed when I use the "full tweet box" on the left panel, but when I try to reply tweets using that "inline box", the confirmation toggle is not displayed so I can't tweet from there.

**Comment by dangeredwolf** [comment]
Resolved. I'll push this one as soon as I work on a few other major but small issues
