### ISSUE TITLE
Button to play/play gifs is not displayed

### ISSUE THREAD

**Issue by seijimaddog** [dangeredwolf/ModernDeck#62]
![problem3](https://cloud.githubusercontent.com/assets/1981720/15429677/71297cf6-1e78-11e6-8cc2-20e9b20d61d9.jpg)

**Comment by dangeredwolf** [comment]
Already fixed actually. In this build you'll just have to click on the gif to pause or play

**Comment by dangeredwolf** [comment]
It isnt quite available yet, so sit tight
