### ISSUE TITLE
retweet dialog looks like shit

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#68]
![screenshot from 2016-06-05 08-38-29](https://cloud.githubusercontent.com/assets/9281956/15805447/f8f535bc-2af8-11e6-8c39-c5eb6633d17f.png)

**Comment by ciolt** [comment]
You're not wrong. 
I'll try and see what I can do on my fork. But, I think that's mainly an issue with how the dialogs now work, by stretching out a small box into a full-blown view on the left side.

**Comment by dangeredwolf** [comment]
@ciolt Once you're done, let me know what you've changed and what it looks like now.

**Comment by ciolt** [comment]
I made the CSS less hacky and let the header wrap the account icons, as well as giving the buttons less strange white space.

![](https://i.gyazo.com/5d632b0a46d979df45bee2647d90d24d.png)

![](https://i.gyazo.com/87c5e58284357abfb03928878651c536.png)

**Comment by joaociocca** [comment]
can we have the option of a mini RT dialog, kinda like Tweeten has? One that pops right on the RT button? (don't mind the lack of icon on the RT button, is what Tweeten shows when running on Wine)

![image](https://user-images.githubusercontent.com/6473725/185772691-3a86b62c-355c-4121-88ea-8190dbdeeb6b.png)
