### ISSUE TITLE
no space between timestamp and username in DM column

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#72]
![screenshot from 2016-06-05 08-41-29](https://cloud.githubusercontent.com/assets/9281956/15805464/7479d67a-2af9-11e6-9911-805b94ffe23f.png)

**Comment by dangeredwolf** [comment]
Complain to whoever's username is giant. I'll also have a look at @ciolt's solution to the issue once he's ready.

**Comment by dangeredwolf** [comment]
I fixed this at some point so consider this issue closed.
