### ISSUE TITLE
search suggestion clear button looks really weird

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#73]
![screenshot from 2016-06-05 08-43-02](https://cloud.githubusercontent.com/assets/9281956/15805467/9678daa0-2af9-11e6-9bb6-c7e9090f6717.png)

**Comment by dangeredwolf** [comment]
Fixed in the latest self-explanatory commit.

**Comment by ashyon** [comment]
still weird :/
what did you fix?
