### ISSUE TITLE
tweet hidden behind filter indicator

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#74]
![screenshot from 2016-06-05 08-43-52](https://cloud.githubusercontent.com/assets/9281956/15805470/b72002ec-2af9-11e6-8dfc-0d0820660bab.png)

**Comment by dangeredwolf** [comment]
Fixed this issue. Please wait while I fix up some other small issues, and I'll sync it with the rest of the source tree.
