### ISSUE TITLE
tweet overflow menu goes too far down, is partially hidden

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#77]
![screenshot from 2016-06-05 08-48-09](https://cloud.githubusercontent.com/assets/9281956/15805489/72fc49d0-2afa-11e6-8a76-705c6a6731a4.png)

**Comment by dangeredwolf** [comment]
Solution: Buy a bigger computer screen. It must be tiny if it can't even fit that context menu in holy shit

**Comment by ashyon** [comment]
I have a 19" screen, that's not a problem. The problem is that the overflow menu is huge and doesn't care if it has room above. It drops downward from the menu button no matter where on the screen it is.

**Comment by ashyon** [comment]
Never mind, it's fixed since the last update

**Comment by ashyon** [comment]
If the overflow menu icon is pressed on a tweet that's about halfway down the screen, it will open downward and go offscreen. Otherwise it opens downward or upward and is fine, but when it is in the middle it should not go all the way down or up so as to not be offscreen
