### ISSUE TITLE
add column button is in weird places throughout the ui

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#79]
![screenshot from 2016-06-05 08-52-46](https://cloud.githubusercontent.com/assets/9281956/15805508/e85369de-2afa-11e6-9361-76682d2a9a40.png)
![screenshot from 2016-06-05 08-52-06](https://cloud.githubusercontent.com/assets/9281956/15805509/e853a462-2afa-11e6-8872-14960dbd3c7d.png)

**Comment by ciolt** [comment]
It's supposed to be awkwardly placed like that.
Removing it would make a lot of people complain, and changing it to a button would make it strange and out of place for Material Design.

![](https://i.gyazo.com/798e98102b3151e037816bc41bb30975.png)
![](https://i.gyazo.com/4d8e63365728b99154538baddf1acb6f.png)

**Comment by dangeredwolf** [comment]
Not a bug, a feature!
