### ISSUE TITLE
Open images from user view in tweetdeck instead of twitter.com

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#81]
![screenshot from 2016-06-05 08-56-49](https://cloud.githubusercontent.com/assets/9281956/15805532/a7963042-2afb-11e6-97c3-cbf56c4c7472.png)

**Comment by dangeredwolf** [comment]
I don't know how to do this, so it's definitely not going to end up being in 6.0. I'll reopen if I consider researching it again.
