### ISSUE TITLE
i'm way too lazy to think of a good issue name for this so hi there are bugs

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#84]
![screenshot from 2016-06-10 19-46-26](https://cloud.githubusercontent.com/assets/9281956/15981481/206a8526-2f44-11e6-9697-6ba9f67dbdaf.png)

**Comment by dangeredwolf** [comment]
Interesting. I'll take a look at this, and probably fix it in the next release.

**Comment by dangeredwolf** [comment]
No longer applicable
