### ISSUE TITLE
image expanded goes below tweet

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#85]
![screenshot from 2016-06-20 09-36-34](https://cloud.githubusercontent.com/assets/9281956/16196109/940595b0-36ca-11e6-801c-f356416a3dd8.png)

**Comment by dangeredwolf** [comment]
What's your screen resolution if you don't mind me asking?

**Comment by ashyon** [comment]
I'm not sure which monitor I took the screenshot from, but I have two - 1366x768 and 1440x960

**Comment by dangeredwolf** [comment]
Since it's been literally years and has probably been fixed by now, I'm gonna go ahead and close the issue.
