### ISSUE TITLE
accounts list sidebar has no shadow

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#89]

**Comment by dangeredwolf** [comment]
Unfortunately, due to tight scheduling, this issue was not patched in the 6.1 update. I hope to fix this issue pretty soon, though!

**Comment by dangeredwolf** [comment]
Oh yeah, also, I can't seem to find a fix for it, because of the way twitter arranges the elements: The columns must be rendered atop the pane, otherwise it'll break the composer view. So I'll mark it as wontfix
