### ISSUE TITLE
Column options/filters not displaying

### ISSUE THREAD

**Issue by kwaio** [dangeredwolf/ModernDeck#90]
![capture](https://cloud.githubusercontent.com/assets/5406429/18012735/08068e2c-6bbb-11e6-96bf-2147109a7c50.PNG)
After clicking either the 3 dots or the check symbol : 
![capture2](https://cloud.githubusercontent.com/assets/5406429/18012734/0804b0fc-6bbb-11e6-80a8-72a2a27fd35e.PNG)
Notice the blue vertical line, the thing might be displayed under the column

**Comment by dangeredwolf** [comment]
Fixed in 6.1, thanks!
