### ISSUE TITLE
Image arrows hidden by large images

### ISSUE THREAD

**Issue by ashkitten** [dangeredwolf/ModernDeck#96]
![2017-01-04-14 01 27](https://cloud.githubusercontent.com/assets/9281956/21655074/71acb176-d286-11e6-8ec0-5d646faf9755.png)

**Comment by dangeredwolf** [comment]
seems fixed

**Comment by dangeredwolf** [comment]
A more permanent fix was implemented in either 7.1 or 7.2 (i forget)
